project_id = "vbbfmmjohdmocnaxgmmd"

[functions.criar-usuario-auth]
verify_jwt = false

[functions.gerar-leads-aniversarios]
verify_jwt = false

[functions.assistente-ia]
verify_jwt = false

[functions.ler-documento-movimentacao]
verify_jwt = false

[functions.alterar-senha-usuario]
verify_jwt = false
