
import { useState, useMemo } from "react";
import { GrupoFavorecido } from "@/types";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { PlusCircle, Search, Filter } from "lucide-react";
import { GrupoFavorecidosForm } from "@/components/grupo-favorecidos/grupo-favorecidos-form";
import { GrupoFavorecidosTable } from "@/components/grupo-favorecidos/grupo-favorecidos-table";
import {
  Card,
  CardContent,
} from "@/components/ui/card";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { toast } from "sonner";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";

// Mock data - in a real app, this would come from a database
const initialGrupos: GrupoFavorecido[] = [
  {
    id: "1",
    nome: "Fornecedores Principais",
    status: "ativo",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "2",
    nome: "Clientes VIP",
    status: "ativo",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "3",
    nome: "Fornecedores Secundários",
    status: "inativo",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export default function GrupoFavorecidosPage() {
  const [grupos, setGrupos] = useState<GrupoFavorecido[]>(initialGrupos);
  const [isDialogOpen, setIsDialogOpen] = useState(false);
  const [editingGrupo, setEditingGrupo] = useState<GrupoFavorecido | undefined>(
    undefined
  );
  
  // Filtros
  const [searchTerm, setSearchTerm] = useState("");
  const [statusFilter, setStatusFilter] = useState<"todos" | "ativo" | "inativo">("todos");

  const handleOpenDialog = (grupo?: GrupoFavorecido) => {
    setEditingGrupo(grupo);
    setIsDialogOpen(true);
  };

  const handleCloseDialog = () => {
    setEditingGrupo(undefined);
    setIsDialogOpen(false);
  };

  const handleSubmit = (data: { nome: string; status: "ativo" | "inativo" }) => {
    if (editingGrupo) {
      // Update existing grupo
      setGrupos((prev) =>
        prev.map((g) =>
          g.id === editingGrupo.id
            ? {
                ...g,
                nome: data.nome,
                status: data.status,
                updatedAt: new Date(),
              }
            : g
        )
      );
      toast.success("Grupo de favorecidos atualizado com sucesso!");
    } else {
      // Create new grupo
      const newGrupo: GrupoFavorecido = {
        id: `${Date.now()}`, // In a real app, this would be generated by the backend
        nome: data.nome,
        status: data.status,
        createdAt: new Date(),
        updatedAt: new Date(),
      };
      setGrupos((prev) => [...prev, newGrupo]);
      toast.success("Grupo de favorecidos criado com sucesso!");
    }
    handleCloseDialog();
  };

  const handleDelete = (id: string) => {
    setGrupos((prev) => prev.filter((grupo) => grupo.id !== id));
    toast.success("Grupo de favorecidos excluído com sucesso!");
  };

  // Aplicar filtros aos grupos
  const filteredGrupos = useMemo(() => {
    return grupos.filter((grupo) => {
      // Filtro por nome
      const matchesSearch = grupo.nome.toLowerCase().includes(searchTerm.toLowerCase());
      
      // Filtro por status
      const matchesStatus = statusFilter === "todos" || grupo.status === statusFilter;
      
      return matchesSearch && matchesStatus;
    });
  }, [grupos, searchTerm, statusFilter]);

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <h1 className="text-2xl font-bold">Grupo de Favorecidos</h1>
        <Button 
          onClick={() => handleOpenDialog()}
          variant="blue"
        >
          <PlusCircle className="mr-2 h-4 w-4" />
          Novo Grupo
        </Button>
      </div>

      <Card>
        <CardContent className="pt-6">
          <div className="mb-6 flex flex-col gap-4 sm:flex-row">
            <div className="relative flex-1">
              <Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground" />
              <Input
                placeholder="Buscar por nome..."
                className="pl-9"
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
              />
            </div>
            <div className="flex w-full sm:w-[180px]">
              <Select
                value={statusFilter}
                onValueChange={(value) => setStatusFilter(value as "todos" | "ativo" | "inativo")}
              >
                <SelectTrigger className="w-full">
                  <Filter className="mr-2 h-4 w-4" />
                  <SelectValue placeholder="Status" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="todos">Todos</SelectItem>
                  <SelectItem value="ativo" className="text-blue-600">Ativo</SelectItem>
                  <SelectItem value="inativo" className="text-red-600">Inativo</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </div>

          <GrupoFavorecidosTable
            grupos={filteredGrupos}
            onEdit={handleOpenDialog}
            onDelete={handleDelete}
          />
        </CardContent>
      </Card>

      <Dialog open={isDialogOpen} onOpenChange={setIsDialogOpen}>
        <DialogContent className="sm:max-w-[500px]">
          <DialogHeader>
            <DialogTitle>
              {editingGrupo
                ? "Editar Grupo de Favorecidos"
                : "Novo Grupo de Favorecidos"}
            </DialogTitle>
          </DialogHeader>
          <GrupoFavorecidosForm
            grupo={editingGrupo}
            onSubmit={handleSubmit}
            onCancel={handleCloseDialog}
          />
        </DialogContent>
      </Dialog>
    </div>
  );
}
