/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BackupRouteImport } from './routes/backup'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as StyleGuideRouteImport } from './routes/style-guide'
import { Route as AdminEmpresasRouteImport } from './routes/admin/empresas'
import { Route as AdminFechamentoMensalRouteImport } from './routes/admin/fechamento-mensal'
import { Route as AdminParametrosRouteImport } from './routes/admin/parametros'
import { Route as AdminUsuariosRouteImport } from './routes/admin/usuarios'
import { Route as AgendaPessoalAgendaUnificadaRouteImport } from './routes/agenda-pessoal/agenda-unificada'
import { Route as AgendaPessoalGoogleAgendaRouteImport } from './routes/agenda-pessoal/google-agenda'
import { Route as AgendaPessoalMetasRouteImport } from './routes/agenda-pessoal/metas'
import { Route as AgendaPessoalPainelRouteImport } from './routes/agenda-pessoal/painel'
import { Route as AgendaPessoalPlanejamentoRouteImport } from './routes/agenda-pessoal/planejamento'
import { Route as AgendaPessoalTarefasRealizadasRouteImport } from './routes/agenda-pessoal/tarefas-realizadas'
import { Route as CadastrosContaCorrenteRouteImport } from './routes/cadastros/conta-corrente'
import { Route as CadastrosFavorecidosRouteImport } from './routes/cadastros/favorecidos'
import { Route as CadastrosGrupoFavorecidosRouteImport } from './routes/cadastros/grupo-favorecidos'
import { Route as CadastrosGrupoProdutosRouteImport } from './routes/cadastros/grupo-produtos'
import { Route as CadastrosImpostosRetidosRouteImport } from './routes/cadastros/impostos-retidos'
import { Route as CadastrosMotivosPerdaRouteImport } from './routes/cadastros/motivos-perda'
import { Route as CadastrosOrigensRouteImport } from './routes/cadastros/origens'
import { Route as CadastrosProfissoesRouteImport } from './routes/cadastros/profissoes'
import { Route as CadastrosTiposTitulosRouteImport } from './routes/cadastros/tipos-titulos'
import { Route as ContabilBalancoRouteImport } from './routes/contabil/balanco'
import { Route as ContabilDreRouteImport } from './routes/contabil/dre'
import { Route as ContabilLancamentosRouteImport } from './routes/contabil/lancamentos'
import { Route as ContabilPlanoContasRouteImport } from './routes/contabil/plano-contas'
import { Route as CrmAgendaRouteImport } from './routes/crm/agenda'
import { Route as CrmFunilConfiguracaoRouteImport } from './routes/crm/funil-configuracao'
import { Route as CrmLeadsRouteImport } from './routes/crm/leads'
import { Route as CrmPainelRouteImport } from './routes/crm/painel'
import { Route as CrmWhatsappRouteImport } from './routes/crm/whatsapp'
import { Route as CrmWhatsappImplantacaoRouteImport } from './routes/crm/whatsapp-implantacao'
import { Route as FinanceiroAntecipacoesRouteImport } from './routes/financeiro/antecipacoes'
import { Route as FinanceiroContasAPagarRouteImport } from './routes/financeiro/contas-a-pagar'
import { Route as FinanceiroContasReceberRouteImport } from './routes/financeiro/contas-receber'
import { Route as FinanceiroFluxoCaixaRouteImport } from './routes/financeiro/fluxo-caixa'
import { Route as FinanceiroIncluirMovimentacaoRouteImport } from './routes/financeiro/incluir-movimentacao'
import { Route as FinanceiroMovimentacaoRouteImport } from './routes/financeiro/movimentacao'
import { Route as FinanceiroPainelFinanceiroRouteImport } from './routes/financeiro/painel-financeiro'
import { Route as RelatoriosIndexRouteImport } from './routes/relatorios/index'
import { Route as RelatoriosAnaliseDreRouteImport } from './routes/relatorios/analise-dre'
import { Route as RelatoriosAniversariantesRouteImport } from './routes/relatorios/aniversariantes'
import { Route as RelatoriosAntecipacoesRouteImport } from './routes/relatorios/antecipacoes'
import { Route as RelatoriosClassificacaoAbcRouteImport } from './routes/relatorios/classificacao-abc'
import { Route as RelatoriosContasAPagarRouteImport } from './routes/relatorios/contas-a-pagar'
import { Route as RelatoriosContasAReceberRouteImport } from './routes/relatorios/contas-a-receber'
import { Route as RelatoriosFavorecidoRouteImport } from './routes/relatorios/favorecido'
import { Route as RelatoriosFinanceiroRouteImport } from './routes/relatorios/financeiro'
import { Route as RelatoriosFotosRouteImport } from './routes/relatorios/fotos'
import { Route as RelatoriosLogsRouteImport } from './routes/relatorios/logs'
import { Route as RelatoriosNotasFiscaisRouteImport } from './routes/relatorios/notas-fiscais'
import { Route as RelatoriosNotasFiscaisRecebidasRouteImport } from './routes/relatorios/notas-fiscais-recebidas'
import { Route as RelatoriosProjetosRouteImport } from './routes/relatorios/projetos'
import { Route as RelatoriosRazaoContabilRouteImport } from './routes/relatorios/razao-contabil'
import { Route as RelatoriosTempoRouteImport } from './routes/relatorios/tempo'
import { Route as RelatoriosVendasRouteImport } from './routes/relatorios/vendas'
import { Route as RelogioIndexRouteImport } from './routes/relogio/index'
import { Route as RelogioApontamentoRouteImport } from './routes/relogio/apontamento'
import { Route as RelogioHorasPorProjetoRouteImport } from './routes/relogio/horas-por-projeto'
import { Route as RelogioPainelProjetosRouteImport } from './routes/relogio/painel-projetos'
import { Route as RelogioPainelTempoRouteImport } from './routes/relogio/painel-tempo'
import { Route as RelogioPlanilhaFotosRouteImport } from './routes/relogio/planilha-fotos'
import { Route as RelogioProjetosRouteImport } from './routes/relogio/projetos'
import { Route as RelogioTiposProjetoRouteImport } from './routes/relogio/tipos-projeto'
import { Route as RelogioVisualizacaoRouteImport } from './routes/relogio/visualizacao'
import { Route as VendasContratosRouteImport } from './routes/vendas/contratos'
import { Route as VendasFaturamentoRouteImport } from './routes/vendas/faturamento'
import { Route as VendasOrcamentoRouteImport } from './routes/vendas/orcamento'
import { Route as VendasPainelVendasRouteImport } from './routes/vendas/painel-vendas'
import { Route as VendasProdutosRouteImport } from './routes/vendas/produtos'
import { Route as VendasServicosRouteImport } from './routes/vendas/servicos'
import { Route as VendasTabelaPrecosRouteImport } from './routes/vendas/tabela-precos'
import { Route as OauthGoogleCalendarReturnRouteImport } from './routes/oauth/google-calendar/return'
import { Route as ApiPublicMetaWebhookRouteImport } from './routes/api/public/meta/webhook'
import { Route as ApiPublicWhatsappWebhookRouteImport } from './routes/api/public/whatsapp/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BackupRoute = BackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const StyleGuideRoute = StyleGuideRouteImport.update({
  id: '/style-guide',
  path: '/style-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEmpresasRoute = AdminEmpresasRouteImport.update({
  id: '/admin/empresas',
  path: '/admin/empresas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFechamentoMensalRoute = AdminFechamentoMensalRouteImport.update({
  id: '/admin/fechamento-mensal',
  path: '/admin/fechamento-mensal',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminParametrosRoute = AdminParametrosRouteImport.update({
  id: '/admin/parametros',
  path: '/admin/parametros',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/admin/usuarios',
  path: '/admin/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaPessoalAgendaUnificadaRoute =
  AgendaPessoalAgendaUnificadaRouteImport.update({
    id: '/agenda-pessoal/agenda-unificada',
    path: '/agenda-pessoal/agenda-unificada',
    getParentRoute: () => rootRouteImport,
  } as any)
const AgendaPessoalGoogleAgendaRoute =
  AgendaPessoalGoogleAgendaRouteImport.update({
    id: '/agenda-pessoal/google-agenda',
    path: '/agenda-pessoal/google-agenda',
    getParentRoute: () => rootRouteImport,
  } as any)
const AgendaPessoalMetasRoute = AgendaPessoalMetasRouteImport.update({
  id: '/agenda-pessoal/metas',
  path: '/agenda-pessoal/metas',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaPessoalPainelRoute = AgendaPessoalPainelRouteImport.update({
  id: '/agenda-pessoal/painel',
  path: '/agenda-pessoal/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaPessoalPlanejamentoRoute =
  AgendaPessoalPlanejamentoRouteImport.update({
    id: '/agenda-pessoal/planejamento',
    path: '/agenda-pessoal/planejamento',
    getParentRoute: () => rootRouteImport,
  } as any)
const AgendaPessoalTarefasRealizadasRoute =
  AgendaPessoalTarefasRealizadasRouteImport.update({
    id: '/agenda-pessoal/tarefas-realizadas',
    path: '/agenda-pessoal/tarefas-realizadas',
    getParentRoute: () => rootRouteImport,
  } as any)
const CadastrosContaCorrenteRoute = CadastrosContaCorrenteRouteImport.update({
  id: '/cadastros/conta-corrente',
  path: '/cadastros/conta-corrente',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastrosFavorecidosRoute = CadastrosFavorecidosRouteImport.update({
  id: '/cadastros/favorecidos',
  path: '/cadastros/favorecidos',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastrosGrupoFavorecidosRoute =
  CadastrosGrupoFavorecidosRouteImport.update({
    id: '/cadastros/grupo-favorecidos',
    path: '/cadastros/grupo-favorecidos',
    getParentRoute: () => rootRouteImport,
  } as any)
const CadastrosGrupoProdutosRoute = CadastrosGrupoProdutosRouteImport.update({
  id: '/cadastros/grupo-produtos',
  path: '/cadastros/grupo-produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastrosImpostosRetidosRoute =
  CadastrosImpostosRetidosRouteImport.update({
    id: '/cadastros/impostos-retidos',
    path: '/cadastros/impostos-retidos',
    getParentRoute: () => rootRouteImport,
  } as any)
const CadastrosMotivosPerdaRoute = CadastrosMotivosPerdaRouteImport.update({
  id: '/cadastros/motivos-perda',
  path: '/cadastros/motivos-perda',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastrosOrigensRoute = CadastrosOrigensRouteImport.update({
  id: '/cadastros/origens',
  path: '/cadastros/origens',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastrosProfissoesRoute = CadastrosProfissoesRouteImport.update({
  id: '/cadastros/profissoes',
  path: '/cadastros/profissoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastrosTiposTitulosRoute = CadastrosTiposTitulosRouteImport.update({
  id: '/cadastros/tipos-titulos',
  path: '/cadastros/tipos-titulos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContabilBalancoRoute = ContabilBalancoRouteImport.update({
  id: '/contabil/balanco',
  path: '/contabil/balanco',
  getParentRoute: () => rootRouteImport,
} as any)
const ContabilDreRoute = ContabilDreRouteImport.update({
  id: '/contabil/dre',
  path: '/contabil/dre',
  getParentRoute: () => rootRouteImport,
} as any)
const ContabilLancamentosRoute = ContabilLancamentosRouteImport.update({
  id: '/contabil/lancamentos',
  path: '/contabil/lancamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContabilPlanoContasRoute = ContabilPlanoContasRouteImport.update({
  id: '/contabil/plano-contas',
  path: '/contabil/plano-contas',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmAgendaRoute = CrmAgendaRouteImport.update({
  id: '/crm/agenda',
  path: '/crm/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmFunilConfiguracaoRoute = CrmFunilConfiguracaoRouteImport.update({
  id: '/crm/funil-configuracao',
  path: '/crm/funil-configuracao',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmLeadsRoute = CrmLeadsRouteImport.update({
  id: '/crm/leads',
  path: '/crm/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmPainelRoute = CrmPainelRouteImport.update({
  id: '/crm/painel',
  path: '/crm/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmWhatsappRoute = CrmWhatsappRouteImport.update({
  id: '/crm/whatsapp',
  path: '/crm/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmWhatsappImplantacaoRoute = CrmWhatsappImplantacaoRouteImport.update({
  id: '/crm/whatsapp-implantacao',
  path: '/crm/whatsapp-implantacao',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroAntecipacoesRoute = FinanceiroAntecipacoesRouteImport.update({
  id: '/financeiro/antecipacoes',
  path: '/financeiro/antecipacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroContasAPagarRoute = FinanceiroContasAPagarRouteImport.update({
  id: '/financeiro/contas-a-pagar',
  path: '/financeiro/contas-a-pagar',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroContasReceberRoute = FinanceiroContasReceberRouteImport.update({
  id: '/financeiro/contas-receber',
  path: '/financeiro/contas-receber',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroFluxoCaixaRoute = FinanceiroFluxoCaixaRouteImport.update({
  id: '/financeiro/fluxo-caixa',
  path: '/financeiro/fluxo-caixa',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroIncluirMovimentacaoRoute =
  FinanceiroIncluirMovimentacaoRouteImport.update({
    id: '/financeiro/incluir-movimentacao',
    path: '/financeiro/incluir-movimentacao',
    getParentRoute: () => rootRouteImport,
  } as any)
const FinanceiroMovimentacaoRoute = FinanceiroMovimentacaoRouteImport.update({
  id: '/financeiro/movimentacao',
  path: '/financeiro/movimentacao',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroPainelFinanceiroRoute =
  FinanceiroPainelFinanceiroRouteImport.update({
    id: '/financeiro/painel-financeiro',
    path: '/financeiro/painel-financeiro',
    getParentRoute: () => rootRouteImport,
  } as any)
const RelatoriosIndexRoute = RelatoriosIndexRouteImport.update({
  id: '/relatorios/',
  path: '/relatorios/',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosAnaliseDreRoute = RelatoriosAnaliseDreRouteImport.update({
  id: '/relatorios/analise-dre',
  path: '/relatorios/analise-dre',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosAniversariantesRoute =
  RelatoriosAniversariantesRouteImport.update({
    id: '/relatorios/aniversariantes',
    path: '/relatorios/aniversariantes',
    getParentRoute: () => rootRouteImport,
  } as any)
const RelatoriosAntecipacoesRoute = RelatoriosAntecipacoesRouteImport.update({
  id: '/relatorios/antecipacoes',
  path: '/relatorios/antecipacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosClassificacaoAbcRoute =
  RelatoriosClassificacaoAbcRouteImport.update({
    id: '/relatorios/classificacao-abc',
    path: '/relatorios/classificacao-abc',
    getParentRoute: () => rootRouteImport,
  } as any)
const RelatoriosContasAPagarRoute = RelatoriosContasAPagarRouteImport.update({
  id: '/relatorios/contas-a-pagar',
  path: '/relatorios/contas-a-pagar',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosContasAReceberRoute =
  RelatoriosContasAReceberRouteImport.update({
    id: '/relatorios/contas-a-receber',
    path: '/relatorios/contas-a-receber',
    getParentRoute: () => rootRouteImport,
  } as any)
const RelatoriosFavorecidoRoute = RelatoriosFavorecidoRouteImport.update({
  id: '/relatorios/favorecido',
  path: '/relatorios/favorecido',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosFinanceiroRoute = RelatoriosFinanceiroRouteImport.update({
  id: '/relatorios/financeiro',
  path: '/relatorios/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosFotosRoute = RelatoriosFotosRouteImport.update({
  id: '/relatorios/fotos',
  path: '/relatorios/fotos',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosLogsRoute = RelatoriosLogsRouteImport.update({
  id: '/relatorios/logs',
  path: '/relatorios/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosNotasFiscaisRoute = RelatoriosNotasFiscaisRouteImport.update({
  id: '/relatorios/notas-fiscais',
  path: '/relatorios/notas-fiscais',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosNotasFiscaisRecebidasRoute =
  RelatoriosNotasFiscaisRecebidasRouteImport.update({
    id: '/relatorios/notas-fiscais-recebidas',
    path: '/relatorios/notas-fiscais-recebidas',
    getParentRoute: () => rootRouteImport,
  } as any)
const RelatoriosProjetosRoute = RelatoriosProjetosRouteImport.update({
  id: '/relatorios/projetos',
  path: '/relatorios/projetos',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRazaoContabilRoute = RelatoriosRazaoContabilRouteImport.update({
  id: '/relatorios/razao-contabil',
  path: '/relatorios/razao-contabil',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosTempoRoute = RelatoriosTempoRouteImport.update({
  id: '/relatorios/tempo',
  path: '/relatorios/tempo',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosVendasRoute = RelatoriosVendasRouteImport.update({
  id: '/relatorios/vendas',
  path: '/relatorios/vendas',
  getParentRoute: () => rootRouteImport,
} as any)
const RelogioIndexRoute = RelogioIndexRouteImport.update({
  id: '/relogio/',
  path: '/relogio/',
  getParentRoute: () => rootRouteImport,
} as any)
const RelogioApontamentoRoute = RelogioApontamentoRouteImport.update({
  id: '/relogio/apontamento',
  path: '/relogio/apontamento',
  getParentRoute: () => rootRouteImport,
} as any)
const RelogioHorasPorProjetoRoute = RelogioHorasPorProjetoRouteImport.update({
  id: '/relogio/horas-por-projeto',
  path: '/relogio/horas-por-projeto',
  getParentRoute: () => rootRouteImport,
} as any)
const RelogioPainelProjetosRoute = RelogioPainelProjetosRouteImport.update({
  id: '/relogio/painel-projetos',
  path: '/relogio/painel-projetos',
  getParentRoute: () => rootRouteImport,
} as any)
const RelogioPainelTempoRoute = RelogioPainelTempoRouteImport.update({
  id: '/relogio/painel-tempo',
  path: '/relogio/painel-tempo',
  getParentRoute: () => rootRouteImport,
} as any)
const RelogioPlanilhaFotosRoute = RelogioPlanilhaFotosRouteImport.update({
  id: '/relogio/planilha-fotos',
  path: '/relogio/planilha-fotos',
  getParentRoute: () => rootRouteImport,
} as any)
const RelogioProjetosRoute = RelogioProjetosRouteImport.update({
  id: '/relogio/projetos',
  path: '/relogio/projetos',
  getParentRoute: () => rootRouteImport,
} as any)
const RelogioTiposProjetoRoute = RelogioTiposProjetoRouteImport.update({
  id: '/relogio/tipos-projeto',
  path: '/relogio/tipos-projeto',
  getParentRoute: () => rootRouteImport,
} as any)
const RelogioVisualizacaoRoute = RelogioVisualizacaoRouteImport.update({
  id: '/relogio/visualizacao',
  path: '/relogio/visualizacao',
  getParentRoute: () => rootRouteImport,
} as any)
const VendasContratosRoute = VendasContratosRouteImport.update({
  id: '/vendas/contratos',
  path: '/vendas/contratos',
  getParentRoute: () => rootRouteImport,
} as any)
const VendasFaturamentoRoute = VendasFaturamentoRouteImport.update({
  id: '/vendas/faturamento',
  path: '/vendas/faturamento',
  getParentRoute: () => rootRouteImport,
} as any)
const VendasOrcamentoRoute = VendasOrcamentoRouteImport.update({
  id: '/vendas/orcamento',
  path: '/vendas/orcamento',
  getParentRoute: () => rootRouteImport,
} as any)
const VendasPainelVendasRoute = VendasPainelVendasRouteImport.update({
  id: '/vendas/painel-vendas',
  path: '/vendas/painel-vendas',
  getParentRoute: () => rootRouteImport,
} as any)
const VendasProdutosRoute = VendasProdutosRouteImport.update({
  id: '/vendas/produtos',
  path: '/vendas/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const VendasServicosRoute = VendasServicosRouteImport.update({
  id: '/vendas/servicos',
  path: '/vendas/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const VendasTabelaPrecosRoute = VendasTabelaPrecosRouteImport.update({
  id: '/vendas/tabela-precos',
  path: '/vendas/tabela-precos',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthGoogleCalendarReturnRoute =
  OauthGoogleCalendarReturnRouteImport.update({
    id: '/oauth/google-calendar/return',
    path: '/oauth/google-calendar/return',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMetaWebhookRoute = ApiPublicMetaWebhookRouteImport.update({
  id: '/api/public/meta/webhook',
  path: '/api/public/meta/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWhatsappWebhookRoute =
  ApiPublicWhatsappWebhookRouteImport.update({
    id: '/api/public/whatsapp/webhook',
    path: '/api/public/whatsapp/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/backup': typeof BackupRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/style-guide': typeof StyleGuideRoute
  '/admin/empresas': typeof AdminEmpresasRoute
  '/admin/fechamento-mensal': typeof AdminFechamentoMensalRoute
  '/admin/parametros': typeof AdminParametrosRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/agenda-pessoal/agenda-unificada': typeof AgendaPessoalAgendaUnificadaRoute
  '/agenda-pessoal/google-agenda': typeof AgendaPessoalGoogleAgendaRoute
  '/agenda-pessoal/metas': typeof AgendaPessoalMetasRoute
  '/agenda-pessoal/painel': typeof AgendaPessoalPainelRoute
  '/agenda-pessoal/planejamento': typeof AgendaPessoalPlanejamentoRoute
  '/agenda-pessoal/tarefas-realizadas': typeof AgendaPessoalTarefasRealizadasRoute
  '/cadastros/conta-corrente': typeof CadastrosContaCorrenteRoute
  '/cadastros/favorecidos': typeof CadastrosFavorecidosRoute
  '/cadastros/grupo-favorecidos': typeof CadastrosGrupoFavorecidosRoute
  '/cadastros/grupo-produtos': typeof CadastrosGrupoProdutosRoute
  '/cadastros/impostos-retidos': typeof CadastrosImpostosRetidosRoute
  '/cadastros/motivos-perda': typeof CadastrosMotivosPerdaRoute
  '/cadastros/origens': typeof CadastrosOrigensRoute
  '/cadastros/profissoes': typeof CadastrosProfissoesRoute
  '/cadastros/tipos-titulos': typeof CadastrosTiposTitulosRoute
  '/contabil/balanco': typeof ContabilBalancoRoute
  '/contabil/dre': typeof ContabilDreRoute
  '/contabil/lancamentos': typeof ContabilLancamentosRoute
  '/contabil/plano-contas': typeof ContabilPlanoContasRoute
  '/crm/agenda': typeof CrmAgendaRoute
  '/crm/funil-configuracao': typeof CrmFunilConfiguracaoRoute
  '/crm/leads': typeof CrmLeadsRoute
  '/crm/painel': typeof CrmPainelRoute
  '/crm/whatsapp': typeof CrmWhatsappRoute
  '/crm/whatsapp-implantacao': typeof CrmWhatsappImplantacaoRoute
  '/financeiro/antecipacoes': typeof FinanceiroAntecipacoesRoute
  '/financeiro/contas-a-pagar': typeof FinanceiroContasAPagarRoute
  '/financeiro/contas-receber': typeof FinanceiroContasReceberRoute
  '/financeiro/fluxo-caixa': typeof FinanceiroFluxoCaixaRoute
  '/financeiro/incluir-movimentacao': typeof FinanceiroIncluirMovimentacaoRoute
  '/financeiro/movimentacao': typeof FinanceiroMovimentacaoRoute
  '/financeiro/painel-financeiro': typeof FinanceiroPainelFinanceiroRoute
  '/relatorios/analise-dre': typeof RelatoriosAnaliseDreRoute
  '/relatorios/aniversariantes': typeof RelatoriosAniversariantesRoute
  '/relatorios/antecipacoes': typeof RelatoriosAntecipacoesRoute
  '/relatorios/classificacao-abc': typeof RelatoriosClassificacaoAbcRoute
  '/relatorios/contas-a-pagar': typeof RelatoriosContasAPagarRoute
  '/relatorios/contas-a-receber': typeof RelatoriosContasAReceberRoute
  '/relatorios/favorecido': typeof RelatoriosFavorecidoRoute
  '/relatorios/financeiro': typeof RelatoriosFinanceiroRoute
  '/relatorios/fotos': typeof RelatoriosFotosRoute
  '/relatorios/logs': typeof RelatoriosLogsRoute
  '/relatorios/notas-fiscais': typeof RelatoriosNotasFiscaisRoute
  '/relatorios/notas-fiscais-recebidas': typeof RelatoriosNotasFiscaisRecebidasRoute
  '/relatorios/projetos': typeof RelatoriosProjetosRoute
  '/relatorios/razao-contabil': typeof RelatoriosRazaoContabilRoute
  '/relatorios/tempo': typeof RelatoriosTempoRoute
  '/relatorios/vendas': typeof RelatoriosVendasRoute
  '/relogio/apontamento': typeof RelogioApontamentoRoute
  '/relogio/horas-por-projeto': typeof RelogioHorasPorProjetoRoute
  '/relogio/painel-projetos': typeof RelogioPainelProjetosRoute
  '/relogio/painel-tempo': typeof RelogioPainelTempoRoute
  '/relogio/planilha-fotos': typeof RelogioPlanilhaFotosRoute
  '/relogio/projetos': typeof RelogioProjetosRoute
  '/relogio/tipos-projeto': typeof RelogioTiposProjetoRoute
  '/relogio/visualizacao': typeof RelogioVisualizacaoRoute
  '/vendas/contratos': typeof VendasContratosRoute
  '/vendas/faturamento': typeof VendasFaturamentoRoute
  '/vendas/orcamento': typeof VendasOrcamentoRoute
  '/vendas/painel-vendas': typeof VendasPainelVendasRoute
  '/vendas/produtos': typeof VendasProdutosRoute
  '/vendas/servicos': typeof VendasServicosRoute
  '/vendas/tabela-precos': typeof VendasTabelaPrecosRoute
  '/relatorios/': typeof RelatoriosIndexRoute
  '/relogio/': typeof RelogioIndexRoute
  '/oauth/google-calendar/return': typeof OauthGoogleCalendarReturnRoute
  '/api/public/meta/webhook': typeof ApiPublicMetaWebhookRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/backup': typeof BackupRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/style-guide': typeof StyleGuideRoute
  '/admin/empresas': typeof AdminEmpresasRoute
  '/admin/fechamento-mensal': typeof AdminFechamentoMensalRoute
  '/admin/parametros': typeof AdminParametrosRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/agenda-pessoal/agenda-unificada': typeof AgendaPessoalAgendaUnificadaRoute
  '/agenda-pessoal/google-agenda': typeof AgendaPessoalGoogleAgendaRoute
  '/agenda-pessoal/metas': typeof AgendaPessoalMetasRoute
  '/agenda-pessoal/painel': typeof AgendaPessoalPainelRoute
  '/agenda-pessoal/planejamento': typeof AgendaPessoalPlanejamentoRoute
  '/agenda-pessoal/tarefas-realizadas': typeof AgendaPessoalTarefasRealizadasRoute
  '/cadastros/conta-corrente': typeof CadastrosContaCorrenteRoute
  '/cadastros/favorecidos': typeof CadastrosFavorecidosRoute
  '/cadastros/grupo-favorecidos': typeof CadastrosGrupoFavorecidosRoute
  '/cadastros/grupo-produtos': typeof CadastrosGrupoProdutosRoute
  '/cadastros/impostos-retidos': typeof CadastrosImpostosRetidosRoute
  '/cadastros/motivos-perda': typeof CadastrosMotivosPerdaRoute
  '/cadastros/origens': typeof CadastrosOrigensRoute
  '/cadastros/profissoes': typeof CadastrosProfissoesRoute
  '/cadastros/tipos-titulos': typeof CadastrosTiposTitulosRoute
  '/contabil/balanco': typeof ContabilBalancoRoute
  '/contabil/dre': typeof ContabilDreRoute
  '/contabil/lancamentos': typeof ContabilLancamentosRoute
  '/contabil/plano-contas': typeof ContabilPlanoContasRoute
  '/crm/agenda': typeof CrmAgendaRoute
  '/crm/funil-configuracao': typeof CrmFunilConfiguracaoRoute
  '/crm/leads': typeof CrmLeadsRoute
  '/crm/painel': typeof CrmPainelRoute
  '/crm/whatsapp': typeof CrmWhatsappRoute
  '/crm/whatsapp-implantacao': typeof CrmWhatsappImplantacaoRoute
  '/financeiro/antecipacoes': typeof FinanceiroAntecipacoesRoute
  '/financeiro/contas-a-pagar': typeof FinanceiroContasAPagarRoute
  '/financeiro/contas-receber': typeof FinanceiroContasReceberRoute
  '/financeiro/fluxo-caixa': typeof FinanceiroFluxoCaixaRoute
  '/financeiro/incluir-movimentacao': typeof FinanceiroIncluirMovimentacaoRoute
  '/financeiro/movimentacao': typeof FinanceiroMovimentacaoRoute
  '/financeiro/painel-financeiro': typeof FinanceiroPainelFinanceiroRoute
  '/relatorios/analise-dre': typeof RelatoriosAnaliseDreRoute
  '/relatorios/aniversariantes': typeof RelatoriosAniversariantesRoute
  '/relatorios/antecipacoes': typeof RelatoriosAntecipacoesRoute
  '/relatorios/classificacao-abc': typeof RelatoriosClassificacaoAbcRoute
  '/relatorios/contas-a-pagar': typeof RelatoriosContasAPagarRoute
  '/relatorios/contas-a-receber': typeof RelatoriosContasAReceberRoute
  '/relatorios/favorecido': typeof RelatoriosFavorecidoRoute
  '/relatorios/financeiro': typeof RelatoriosFinanceiroRoute
  '/relatorios/fotos': typeof RelatoriosFotosRoute
  '/relatorios/logs': typeof RelatoriosLogsRoute
  '/relatorios/notas-fiscais': typeof RelatoriosNotasFiscaisRoute
  '/relatorios/notas-fiscais-recebidas': typeof RelatoriosNotasFiscaisRecebidasRoute
  '/relatorios/projetos': typeof RelatoriosProjetosRoute
  '/relatorios/razao-contabil': typeof RelatoriosRazaoContabilRoute
  '/relatorios/tempo': typeof RelatoriosTempoRoute
  '/relatorios/vendas': typeof RelatoriosVendasRoute
  '/relogio/apontamento': typeof RelogioApontamentoRoute
  '/relogio/horas-por-projeto': typeof RelogioHorasPorProjetoRoute
  '/relogio/painel-projetos': typeof RelogioPainelProjetosRoute
  '/relogio/painel-tempo': typeof RelogioPainelTempoRoute
  '/relogio/planilha-fotos': typeof RelogioPlanilhaFotosRoute
  '/relogio/projetos': typeof RelogioProjetosRoute
  '/relogio/tipos-projeto': typeof RelogioTiposProjetoRoute
  '/relogio/visualizacao': typeof RelogioVisualizacaoRoute
  '/vendas/contratos': typeof VendasContratosRoute
  '/vendas/faturamento': typeof VendasFaturamentoRoute
  '/vendas/orcamento': typeof VendasOrcamentoRoute
  '/vendas/painel-vendas': typeof VendasPainelVendasRoute
  '/vendas/produtos': typeof VendasProdutosRoute
  '/vendas/servicos': typeof VendasServicosRoute
  '/vendas/tabela-precos': typeof VendasTabelaPrecosRoute
  '/relatorios': typeof RelatoriosIndexRoute
  '/relogio': typeof RelogioIndexRoute
  '/oauth/google-calendar/return': typeof OauthGoogleCalendarReturnRoute
  '/api/public/meta/webhook': typeof ApiPublicMetaWebhookRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/backup': typeof BackupRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/style-guide': typeof StyleGuideRoute
  '/admin/empresas': typeof AdminEmpresasRoute
  '/admin/fechamento-mensal': typeof AdminFechamentoMensalRoute
  '/admin/parametros': typeof AdminParametrosRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/agenda-pessoal/agenda-unificada': typeof AgendaPessoalAgendaUnificadaRoute
  '/agenda-pessoal/google-agenda': typeof AgendaPessoalGoogleAgendaRoute
  '/agenda-pessoal/metas': typeof AgendaPessoalMetasRoute
  '/agenda-pessoal/painel': typeof AgendaPessoalPainelRoute
  '/agenda-pessoal/planejamento': typeof AgendaPessoalPlanejamentoRoute
  '/agenda-pessoal/tarefas-realizadas': typeof AgendaPessoalTarefasRealizadasRoute
  '/cadastros/conta-corrente': typeof CadastrosContaCorrenteRoute
  '/cadastros/favorecidos': typeof CadastrosFavorecidosRoute
  '/cadastros/grupo-favorecidos': typeof CadastrosGrupoFavorecidosRoute
  '/cadastros/grupo-produtos': typeof CadastrosGrupoProdutosRoute
  '/cadastros/impostos-retidos': typeof CadastrosImpostosRetidosRoute
  '/cadastros/motivos-perda': typeof CadastrosMotivosPerdaRoute
  '/cadastros/origens': typeof CadastrosOrigensRoute
  '/cadastros/profissoes': typeof CadastrosProfissoesRoute
  '/cadastros/tipos-titulos': typeof CadastrosTiposTitulosRoute
  '/contabil/balanco': typeof ContabilBalancoRoute
  '/contabil/dre': typeof ContabilDreRoute
  '/contabil/lancamentos': typeof ContabilLancamentosRoute
  '/contabil/plano-contas': typeof ContabilPlanoContasRoute
  '/crm/agenda': typeof CrmAgendaRoute
  '/crm/funil-configuracao': typeof CrmFunilConfiguracaoRoute
  '/crm/leads': typeof CrmLeadsRoute
  '/crm/painel': typeof CrmPainelRoute
  '/crm/whatsapp': typeof CrmWhatsappRoute
  '/crm/whatsapp-implantacao': typeof CrmWhatsappImplantacaoRoute
  '/financeiro/antecipacoes': typeof FinanceiroAntecipacoesRoute
  '/financeiro/contas-a-pagar': typeof FinanceiroContasAPagarRoute
  '/financeiro/contas-receber': typeof FinanceiroContasReceberRoute
  '/financeiro/fluxo-caixa': typeof FinanceiroFluxoCaixaRoute
  '/financeiro/incluir-movimentacao': typeof FinanceiroIncluirMovimentacaoRoute
  '/financeiro/movimentacao': typeof FinanceiroMovimentacaoRoute
  '/financeiro/painel-financeiro': typeof FinanceiroPainelFinanceiroRoute
  '/relatorios/analise-dre': typeof RelatoriosAnaliseDreRoute
  '/relatorios/aniversariantes': typeof RelatoriosAniversariantesRoute
  '/relatorios/antecipacoes': typeof RelatoriosAntecipacoesRoute
  '/relatorios/classificacao-abc': typeof RelatoriosClassificacaoAbcRoute
  '/relatorios/contas-a-pagar': typeof RelatoriosContasAPagarRoute
  '/relatorios/contas-a-receber': typeof RelatoriosContasAReceberRoute
  '/relatorios/favorecido': typeof RelatoriosFavorecidoRoute
  '/relatorios/financeiro': typeof RelatoriosFinanceiroRoute
  '/relatorios/fotos': typeof RelatoriosFotosRoute
  '/relatorios/logs': typeof RelatoriosLogsRoute
  '/relatorios/notas-fiscais': typeof RelatoriosNotasFiscaisRoute
  '/relatorios/notas-fiscais-recebidas': typeof RelatoriosNotasFiscaisRecebidasRoute
  '/relatorios/projetos': typeof RelatoriosProjetosRoute
  '/relatorios/razao-contabil': typeof RelatoriosRazaoContabilRoute
  '/relatorios/tempo': typeof RelatoriosTempoRoute
  '/relatorios/vendas': typeof RelatoriosVendasRoute
  '/relogio/apontamento': typeof RelogioApontamentoRoute
  '/relogio/horas-por-projeto': typeof RelogioHorasPorProjetoRoute
  '/relogio/painel-projetos': typeof RelogioPainelProjetosRoute
  '/relogio/painel-tempo': typeof RelogioPainelTempoRoute
  '/relogio/planilha-fotos': typeof RelogioPlanilhaFotosRoute
  '/relogio/projetos': typeof RelogioProjetosRoute
  '/relogio/tipos-projeto': typeof RelogioTiposProjetoRoute
  '/relogio/visualizacao': typeof RelogioVisualizacaoRoute
  '/vendas/contratos': typeof VendasContratosRoute
  '/vendas/faturamento': typeof VendasFaturamentoRoute
  '/vendas/orcamento': typeof VendasOrcamentoRoute
  '/vendas/painel-vendas': typeof VendasPainelVendasRoute
  '/vendas/produtos': typeof VendasProdutosRoute
  '/vendas/servicos': typeof VendasServicosRoute
  '/vendas/tabela-precos': typeof VendasTabelaPrecosRoute
  '/relatorios/': typeof RelatoriosIndexRoute
  '/relogio/': typeof RelogioIndexRoute
  '/oauth/google-calendar/return': typeof OauthGoogleCalendarReturnRoute
  '/api/public/meta/webhook': typeof ApiPublicMetaWebhookRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/backup'
    | '/dashboard'
    | '/login'
    | '/style-guide'
    | '/admin/empresas'
    | '/admin/fechamento-mensal'
    | '/admin/parametros'
    | '/admin/usuarios'
    | '/agenda-pessoal/agenda-unificada'
    | '/agenda-pessoal/google-agenda'
    | '/agenda-pessoal/metas'
    | '/agenda-pessoal/painel'
    | '/agenda-pessoal/planejamento'
    | '/agenda-pessoal/tarefas-realizadas'
    | '/cadastros/conta-corrente'
    | '/cadastros/favorecidos'
    | '/cadastros/grupo-favorecidos'
    | '/cadastros/grupo-produtos'
    | '/cadastros/impostos-retidos'
    | '/cadastros/motivos-perda'
    | '/cadastros/origens'
    | '/cadastros/profissoes'
    | '/cadastros/tipos-titulos'
    | '/contabil/balanco'
    | '/contabil/dre'
    | '/contabil/lancamentos'
    | '/contabil/plano-contas'
    | '/crm/agenda'
    | '/crm/funil-configuracao'
    | '/crm/leads'
    | '/crm/painel'
    | '/crm/whatsapp'
    | '/crm/whatsapp-implantacao'
    | '/financeiro/antecipacoes'
    | '/financeiro/contas-a-pagar'
    | '/financeiro/contas-receber'
    | '/financeiro/fluxo-caixa'
    | '/financeiro/incluir-movimentacao'
    | '/financeiro/movimentacao'
    | '/financeiro/painel-financeiro'
    | '/relatorios/analise-dre'
    | '/relatorios/aniversariantes'
    | '/relatorios/antecipacoes'
    | '/relatorios/classificacao-abc'
    | '/relatorios/contas-a-pagar'
    | '/relatorios/contas-a-receber'
    | '/relatorios/favorecido'
    | '/relatorios/financeiro'
    | '/relatorios/fotos'
    | '/relatorios/logs'
    | '/relatorios/notas-fiscais'
    | '/relatorios/notas-fiscais-recebidas'
    | '/relatorios/projetos'
    | '/relatorios/razao-contabil'
    | '/relatorios/tempo'
    | '/relatorios/vendas'
    | '/relogio/apontamento'
    | '/relogio/horas-por-projeto'
    | '/relogio/painel-projetos'
    | '/relogio/painel-tempo'
    | '/relogio/planilha-fotos'
    | '/relogio/projetos'
    | '/relogio/tipos-projeto'
    | '/relogio/visualizacao'
    | '/vendas/contratos'
    | '/vendas/faturamento'
    | '/vendas/orcamento'
    | '/vendas/painel-vendas'
    | '/vendas/produtos'
    | '/vendas/servicos'
    | '/vendas/tabela-precos'
    | '/relatorios/'
    | '/relogio/'
    | '/oauth/google-calendar/return'
    | '/api/public/meta/webhook'
    | '/api/public/whatsapp/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/backup'
    | '/dashboard'
    | '/login'
    | '/style-guide'
    | '/admin/empresas'
    | '/admin/fechamento-mensal'
    | '/admin/parametros'
    | '/admin/usuarios'
    | '/agenda-pessoal/agenda-unificada'
    | '/agenda-pessoal/google-agenda'
    | '/agenda-pessoal/metas'
    | '/agenda-pessoal/painel'
    | '/agenda-pessoal/planejamento'
    | '/agenda-pessoal/tarefas-realizadas'
    | '/cadastros/conta-corrente'
    | '/cadastros/favorecidos'
    | '/cadastros/grupo-favorecidos'
    | '/cadastros/grupo-produtos'
    | '/cadastros/impostos-retidos'
    | '/cadastros/motivos-perda'
    | '/cadastros/origens'
    | '/cadastros/profissoes'
    | '/cadastros/tipos-titulos'
    | '/contabil/balanco'
    | '/contabil/dre'
    | '/contabil/lancamentos'
    | '/contabil/plano-contas'
    | '/crm/agenda'
    | '/crm/funil-configuracao'
    | '/crm/leads'
    | '/crm/painel'
    | '/crm/whatsapp'
    | '/crm/whatsapp-implantacao'
    | '/financeiro/antecipacoes'
    | '/financeiro/contas-a-pagar'
    | '/financeiro/contas-receber'
    | '/financeiro/fluxo-caixa'
    | '/financeiro/incluir-movimentacao'
    | '/financeiro/movimentacao'
    | '/financeiro/painel-financeiro'
    | '/relatorios/analise-dre'
    | '/relatorios/aniversariantes'
    | '/relatorios/antecipacoes'
    | '/relatorios/classificacao-abc'
    | '/relatorios/contas-a-pagar'
    | '/relatorios/contas-a-receber'
    | '/relatorios/favorecido'
    | '/relatorios/financeiro'
    | '/relatorios/fotos'
    | '/relatorios/logs'
    | '/relatorios/notas-fiscais'
    | '/relatorios/notas-fiscais-recebidas'
    | '/relatorios/projetos'
    | '/relatorios/razao-contabil'
    | '/relatorios/tempo'
    | '/relatorios/vendas'
    | '/relogio/apontamento'
    | '/relogio/horas-por-projeto'
    | '/relogio/painel-projetos'
    | '/relogio/painel-tempo'
    | '/relogio/planilha-fotos'
    | '/relogio/projetos'
    | '/relogio/tipos-projeto'
    | '/relogio/visualizacao'
    | '/vendas/contratos'
    | '/vendas/faturamento'
    | '/vendas/orcamento'
    | '/vendas/painel-vendas'
    | '/vendas/produtos'
    | '/vendas/servicos'
    | '/vendas/tabela-precos'
    | '/relatorios'
    | '/relogio'
    | '/oauth/google-calendar/return'
    | '/api/public/meta/webhook'
    | '/api/public/whatsapp/webhook'
  id:
    | '__root__'
    | '/'
    | '/backup'
    | '/dashboard'
    | '/login'
    | '/style-guide'
    | '/admin/empresas'
    | '/admin/fechamento-mensal'
    | '/admin/parametros'
    | '/admin/usuarios'
    | '/agenda-pessoal/agenda-unificada'
    | '/agenda-pessoal/google-agenda'
    | '/agenda-pessoal/metas'
    | '/agenda-pessoal/painel'
    | '/agenda-pessoal/planejamento'
    | '/agenda-pessoal/tarefas-realizadas'
    | '/cadastros/conta-corrente'
    | '/cadastros/favorecidos'
    | '/cadastros/grupo-favorecidos'
    | '/cadastros/grupo-produtos'
    | '/cadastros/impostos-retidos'
    | '/cadastros/motivos-perda'
    | '/cadastros/origens'
    | '/cadastros/profissoes'
    | '/cadastros/tipos-titulos'
    | '/contabil/balanco'
    | '/contabil/dre'
    | '/contabil/lancamentos'
    | '/contabil/plano-contas'
    | '/crm/agenda'
    | '/crm/funil-configuracao'
    | '/crm/leads'
    | '/crm/painel'
    | '/crm/whatsapp'
    | '/crm/whatsapp-implantacao'
    | '/financeiro/antecipacoes'
    | '/financeiro/contas-a-pagar'
    | '/financeiro/contas-receber'
    | '/financeiro/fluxo-caixa'
    | '/financeiro/incluir-movimentacao'
    | '/financeiro/movimentacao'
    | '/financeiro/painel-financeiro'
    | '/relatorios/analise-dre'
    | '/relatorios/aniversariantes'
    | '/relatorios/antecipacoes'
    | '/relatorios/classificacao-abc'
    | '/relatorios/contas-a-pagar'
    | '/relatorios/contas-a-receber'
    | '/relatorios/favorecido'
    | '/relatorios/financeiro'
    | '/relatorios/fotos'
    | '/relatorios/logs'
    | '/relatorios/notas-fiscais'
    | '/relatorios/notas-fiscais-recebidas'
    | '/relatorios/projetos'
    | '/relatorios/razao-contabil'
    | '/relatorios/tempo'
    | '/relatorios/vendas'
    | '/relogio/apontamento'
    | '/relogio/horas-por-projeto'
    | '/relogio/painel-projetos'
    | '/relogio/painel-tempo'
    | '/relogio/planilha-fotos'
    | '/relogio/projetos'
    | '/relogio/tipos-projeto'
    | '/relogio/visualizacao'
    | '/vendas/contratos'
    | '/vendas/faturamento'
    | '/vendas/orcamento'
    | '/vendas/painel-vendas'
    | '/vendas/produtos'
    | '/vendas/servicos'
    | '/vendas/tabela-precos'
    | '/relatorios/'
    | '/relogio/'
    | '/oauth/google-calendar/return'
    | '/api/public/meta/webhook'
    | '/api/public/whatsapp/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BackupRoute: typeof BackupRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  StyleGuideRoute: typeof StyleGuideRoute
  AdminEmpresasRoute: typeof AdminEmpresasRoute
  AdminFechamentoMensalRoute: typeof AdminFechamentoMensalRoute
  AdminParametrosRoute: typeof AdminParametrosRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AgendaPessoalAgendaUnificadaRoute: typeof AgendaPessoalAgendaUnificadaRoute
  AgendaPessoalGoogleAgendaRoute: typeof AgendaPessoalGoogleAgendaRoute
  AgendaPessoalMetasRoute: typeof AgendaPessoalMetasRoute
  AgendaPessoalPainelRoute: typeof AgendaPessoalPainelRoute
  AgendaPessoalPlanejamentoRoute: typeof AgendaPessoalPlanejamentoRoute
  AgendaPessoalTarefasRealizadasRoute: typeof AgendaPessoalTarefasRealizadasRoute
  CadastrosContaCorrenteRoute: typeof CadastrosContaCorrenteRoute
  CadastrosFavorecidosRoute: typeof CadastrosFavorecidosRoute
  CadastrosGrupoFavorecidosRoute: typeof CadastrosGrupoFavorecidosRoute
  CadastrosGrupoProdutosRoute: typeof CadastrosGrupoProdutosRoute
  CadastrosImpostosRetidosRoute: typeof CadastrosImpostosRetidosRoute
  CadastrosMotivosPerdaRoute: typeof CadastrosMotivosPerdaRoute
  CadastrosOrigensRoute: typeof CadastrosOrigensRoute
  CadastrosProfissoesRoute: typeof CadastrosProfissoesRoute
  CadastrosTiposTitulosRoute: typeof CadastrosTiposTitulosRoute
  ContabilBalancoRoute: typeof ContabilBalancoRoute
  ContabilDreRoute: typeof ContabilDreRoute
  ContabilLancamentosRoute: typeof ContabilLancamentosRoute
  ContabilPlanoContasRoute: typeof ContabilPlanoContasRoute
  CrmAgendaRoute: typeof CrmAgendaRoute
  CrmFunilConfiguracaoRoute: typeof CrmFunilConfiguracaoRoute
  CrmLeadsRoute: typeof CrmLeadsRoute
  CrmPainelRoute: typeof CrmPainelRoute
  CrmWhatsappRoute: typeof CrmWhatsappRoute
  CrmWhatsappImplantacaoRoute: typeof CrmWhatsappImplantacaoRoute
  FinanceiroAntecipacoesRoute: typeof FinanceiroAntecipacoesRoute
  FinanceiroContasAPagarRoute: typeof FinanceiroContasAPagarRoute
  FinanceiroContasReceberRoute: typeof FinanceiroContasReceberRoute
  FinanceiroFluxoCaixaRoute: typeof FinanceiroFluxoCaixaRoute
  FinanceiroIncluirMovimentacaoRoute: typeof FinanceiroIncluirMovimentacaoRoute
  FinanceiroMovimentacaoRoute: typeof FinanceiroMovimentacaoRoute
  FinanceiroPainelFinanceiroRoute: typeof FinanceiroPainelFinanceiroRoute
  RelatoriosAnaliseDreRoute: typeof RelatoriosAnaliseDreRoute
  RelatoriosAniversariantesRoute: typeof RelatoriosAniversariantesRoute
  RelatoriosAntecipacoesRoute: typeof RelatoriosAntecipacoesRoute
  RelatoriosClassificacaoAbcRoute: typeof RelatoriosClassificacaoAbcRoute
  RelatoriosContasAPagarRoute: typeof RelatoriosContasAPagarRoute
  RelatoriosContasAReceberRoute: typeof RelatoriosContasAReceberRoute
  RelatoriosFavorecidoRoute: typeof RelatoriosFavorecidoRoute
  RelatoriosFinanceiroRoute: typeof RelatoriosFinanceiroRoute
  RelatoriosFotosRoute: typeof RelatoriosFotosRoute
  RelatoriosLogsRoute: typeof RelatoriosLogsRoute
  RelatoriosNotasFiscaisRoute: typeof RelatoriosNotasFiscaisRoute
  RelatoriosNotasFiscaisRecebidasRoute: typeof RelatoriosNotasFiscaisRecebidasRoute
  RelatoriosProjetosRoute: typeof RelatoriosProjetosRoute
  RelatoriosRazaoContabilRoute: typeof RelatoriosRazaoContabilRoute
  RelatoriosTempoRoute: typeof RelatoriosTempoRoute
  RelatoriosVendasRoute: typeof RelatoriosVendasRoute
  RelogioApontamentoRoute: typeof RelogioApontamentoRoute
  RelogioHorasPorProjetoRoute: typeof RelogioHorasPorProjetoRoute
  RelogioPainelProjetosRoute: typeof RelogioPainelProjetosRoute
  RelogioPainelTempoRoute: typeof RelogioPainelTempoRoute
  RelogioPlanilhaFotosRoute: typeof RelogioPlanilhaFotosRoute
  RelogioProjetosRoute: typeof RelogioProjetosRoute
  RelogioTiposProjetoRoute: typeof RelogioTiposProjetoRoute
  RelogioVisualizacaoRoute: typeof RelogioVisualizacaoRoute
  VendasContratosRoute: typeof VendasContratosRoute
  VendasFaturamentoRoute: typeof VendasFaturamentoRoute
  VendasOrcamentoRoute: typeof VendasOrcamentoRoute
  VendasPainelVendasRoute: typeof VendasPainelVendasRoute
  VendasProdutosRoute: typeof VendasProdutosRoute
  VendasServicosRoute: typeof VendasServicosRoute
  VendasTabelaPrecosRoute: typeof VendasTabelaPrecosRoute
  RelatoriosIndexRoute: typeof RelatoriosIndexRoute
  RelogioIndexRoute: typeof RelogioIndexRoute
  OauthGoogleCalendarReturnRoute: typeof OauthGoogleCalendarReturnRoute
  ApiPublicMetaWebhookRoute: typeof ApiPublicMetaWebhookRoute
  ApiPublicWhatsappWebhookRoute: typeof ApiPublicWhatsappWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backup': {
      id: '/backup'
      path: '/backup'
      fullPath: '/backup'
      preLoaderRoute: typeof BackupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/style-guide': {
      id: '/style-guide'
      path: '/style-guide'
      fullPath: '/style-guide'
      preLoaderRoute: typeof StyleGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/empresas': {
      id: '/admin/empresas'
      path: '/admin/empresas'
      fullPath: '/admin/empresas'
      preLoaderRoute: typeof AdminEmpresasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/fechamento-mensal': {
      id: '/admin/fechamento-mensal'
      path: '/admin/fechamento-mensal'
      fullPath: '/admin/fechamento-mensal'
      preLoaderRoute: typeof AdminFechamentoMensalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/parametros': {
      id: '/admin/parametros'
      path: '/admin/parametros'
      fullPath: '/admin/parametros'
      preLoaderRoute: typeof AdminParametrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda-pessoal/agenda-unificada': {
      id: '/agenda-pessoal/agenda-unificada'
      path: '/agenda-pessoal/agenda-unificada'
      fullPath: '/agenda-pessoal/agenda-unificada'
      preLoaderRoute: typeof AgendaPessoalAgendaUnificadaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda-pessoal/google-agenda': {
      id: '/agenda-pessoal/google-agenda'
      path: '/agenda-pessoal/google-agenda'
      fullPath: '/agenda-pessoal/google-agenda'
      preLoaderRoute: typeof AgendaPessoalGoogleAgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda-pessoal/metas': {
      id: '/agenda-pessoal/metas'
      path: '/agenda-pessoal/metas'
      fullPath: '/agenda-pessoal/metas'
      preLoaderRoute: typeof AgendaPessoalMetasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda-pessoal/painel': {
      id: '/agenda-pessoal/painel'
      path: '/agenda-pessoal/painel'
      fullPath: '/agenda-pessoal/painel'
      preLoaderRoute: typeof AgendaPessoalPainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda-pessoal/planejamento': {
      id: '/agenda-pessoal/planejamento'
      path: '/agenda-pessoal/planejamento'
      fullPath: '/agenda-pessoal/planejamento'
      preLoaderRoute: typeof AgendaPessoalPlanejamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda-pessoal/tarefas-realizadas': {
      id: '/agenda-pessoal/tarefas-realizadas'
      path: '/agenda-pessoal/tarefas-realizadas'
      fullPath: '/agenda-pessoal/tarefas-realizadas'
      preLoaderRoute: typeof AgendaPessoalTarefasRealizadasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastros/conta-corrente': {
      id: '/cadastros/conta-corrente'
      path: '/cadastros/conta-corrente'
      fullPath: '/cadastros/conta-corrente'
      preLoaderRoute: typeof CadastrosContaCorrenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastros/favorecidos': {
      id: '/cadastros/favorecidos'
      path: '/cadastros/favorecidos'
      fullPath: '/cadastros/favorecidos'
      preLoaderRoute: typeof CadastrosFavorecidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastros/grupo-favorecidos': {
      id: '/cadastros/grupo-favorecidos'
      path: '/cadastros/grupo-favorecidos'
      fullPath: '/cadastros/grupo-favorecidos'
      preLoaderRoute: typeof CadastrosGrupoFavorecidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastros/grupo-produtos': {
      id: '/cadastros/grupo-produtos'
      path: '/cadastros/grupo-produtos'
      fullPath: '/cadastros/grupo-produtos'
      preLoaderRoute: typeof CadastrosGrupoProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastros/impostos-retidos': {
      id: '/cadastros/impostos-retidos'
      path: '/cadastros/impostos-retidos'
      fullPath: '/cadastros/impostos-retidos'
      preLoaderRoute: typeof CadastrosImpostosRetidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastros/motivos-perda': {
      id: '/cadastros/motivos-perda'
      path: '/cadastros/motivos-perda'
      fullPath: '/cadastros/motivos-perda'
      preLoaderRoute: typeof CadastrosMotivosPerdaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastros/origens': {
      id: '/cadastros/origens'
      path: '/cadastros/origens'
      fullPath: '/cadastros/origens'
      preLoaderRoute: typeof CadastrosOrigensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastros/profissoes': {
      id: '/cadastros/profissoes'
      path: '/cadastros/profissoes'
      fullPath: '/cadastros/profissoes'
      preLoaderRoute: typeof CadastrosProfissoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastros/tipos-titulos': {
      id: '/cadastros/tipos-titulos'
      path: '/cadastros/tipos-titulos'
      fullPath: '/cadastros/tipos-titulos'
      preLoaderRoute: typeof CadastrosTiposTitulosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contabil/balanco': {
      id: '/contabil/balanco'
      path: '/contabil/balanco'
      fullPath: '/contabil/balanco'
      preLoaderRoute: typeof ContabilBalancoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contabil/dre': {
      id: '/contabil/dre'
      path: '/contabil/dre'
      fullPath: '/contabil/dre'
      preLoaderRoute: typeof ContabilDreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contabil/lancamentos': {
      id: '/contabil/lancamentos'
      path: '/contabil/lancamentos'
      fullPath: '/contabil/lancamentos'
      preLoaderRoute: typeof ContabilLancamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contabil/plano-contas': {
      id: '/contabil/plano-contas'
      path: '/contabil/plano-contas'
      fullPath: '/contabil/plano-contas'
      preLoaderRoute: typeof ContabilPlanoContasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/agenda': {
      id: '/crm/agenda'
      path: '/crm/agenda'
      fullPath: '/crm/agenda'
      preLoaderRoute: typeof CrmAgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/funil-configuracao': {
      id: '/crm/funil-configuracao'
      path: '/crm/funil-configuracao'
      fullPath: '/crm/funil-configuracao'
      preLoaderRoute: typeof CrmFunilConfiguracaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/leads': {
      id: '/crm/leads'
      path: '/crm/leads'
      fullPath: '/crm/leads'
      preLoaderRoute: typeof CrmLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/painel': {
      id: '/crm/painel'
      path: '/crm/painel'
      fullPath: '/crm/painel'
      preLoaderRoute: typeof CrmPainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/whatsapp': {
      id: '/crm/whatsapp'
      path: '/crm/whatsapp'
      fullPath: '/crm/whatsapp'
      preLoaderRoute: typeof CrmWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/whatsapp-implantacao': {
      id: '/crm/whatsapp-implantacao'
      path: '/crm/whatsapp-implantacao'
      fullPath: '/crm/whatsapp-implantacao'
      preLoaderRoute: typeof CrmWhatsappImplantacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro/antecipacoes': {
      id: '/financeiro/antecipacoes'
      path: '/financeiro/antecipacoes'
      fullPath: '/financeiro/antecipacoes'
      preLoaderRoute: typeof FinanceiroAntecipacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro/contas-a-pagar': {
      id: '/financeiro/contas-a-pagar'
      path: '/financeiro/contas-a-pagar'
      fullPath: '/financeiro/contas-a-pagar'
      preLoaderRoute: typeof FinanceiroContasAPagarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro/contas-receber': {
      id: '/financeiro/contas-receber'
      path: '/financeiro/contas-receber'
      fullPath: '/financeiro/contas-receber'
      preLoaderRoute: typeof FinanceiroContasReceberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro/fluxo-caixa': {
      id: '/financeiro/fluxo-caixa'
      path: '/financeiro/fluxo-caixa'
      fullPath: '/financeiro/fluxo-caixa'
      preLoaderRoute: typeof FinanceiroFluxoCaixaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro/incluir-movimentacao': {
      id: '/financeiro/incluir-movimentacao'
      path: '/financeiro/incluir-movimentacao'
      fullPath: '/financeiro/incluir-movimentacao'
      preLoaderRoute: typeof FinanceiroIncluirMovimentacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro/movimentacao': {
      id: '/financeiro/movimentacao'
      path: '/financeiro/movimentacao'
      fullPath: '/financeiro/movimentacao'
      preLoaderRoute: typeof FinanceiroMovimentacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro/painel-financeiro': {
      id: '/financeiro/painel-financeiro'
      path: '/financeiro/painel-financeiro'
      fullPath: '/financeiro/painel-financeiro'
      preLoaderRoute: typeof FinanceiroPainelFinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios/': {
      id: '/relatorios/'
      path: '/relatorios'
      fullPath: '/relatorios/'
      preLoaderRoute: typeof RelatoriosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios/analise-dre': {
      id: '/relatorios/analise-dre'
      path: '/relatorios/analise-dre'
      fullPath: '/relatorios/analise-dre'
      preLoaderRoute: typeof RelatoriosAnaliseDreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios/aniversariantes': {
      id: '/relatorios/aniversariantes'
      path: '/relatorios/aniversariantes'
      fullPath: '/relatorios/aniversariantes'
      preLoaderRoute: typeof RelatoriosAniversariantesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios/antecipacoes': {
      id: '/relatorios/antecipacoes'
      path: '/relatorios/antecipacoes'
      fullPath: '/relatorios/antecipacoes'
      preLoaderRoute: typeof RelatoriosAntecipacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios/classificacao-abc': {
      id: '/relatorios/classificacao-abc'
      path: '/relatorios/classificacao-abc'
      fullPath: '/relatorios/classificacao-abc'
      preLoaderRoute: typeof RelatoriosClassificacaoAbcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios/contas-a-pagar': {
      id: '/relatorios/contas-a-pagar'
      path: '/relatorios/contas-a-pagar'
      fullPath: '/relatorios/contas-a-pagar'
      preLoaderRoute: typeof RelatoriosContasAPagarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios/contas-a-receber': {
      id: '/relatorios/contas-a-receber'
      path: '/relatorios/contas-a-receber'
      fullPath: '/relatorios/contas-a-receber'
      preLoaderRoute: typeof RelatoriosContasAReceberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios/favorecido': {
      id: '/relatorios/favorecido'
      path: '/relatorios/favorecido'
      fullPath: '/relatorios/favorecido'
      preLoaderRoute: typeof RelatoriosFavorecidoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios/financeiro': {
      id: '/relatorios/financeiro'
      path: '/relatorios/financeiro'
      fullPath: '/relatorios/financeiro'
      preLoaderRoute: typeof RelatoriosFinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios/fotos': {
      id: '/relatorios/fotos'
      path: '/relatorios/fotos'
      fullPath: '/relatorios/fotos'
      preLoaderRoute: typeof RelatoriosFotosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios/logs': {
      id: '/relatorios/logs'
      path: '/relatorios/logs'
      fullPath: '/relatorios/logs'
      preLoaderRoute: typeof RelatoriosLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios/notas-fiscais': {
      id: '/relatorios/notas-fiscais'
      path: '/relatorios/notas-fiscais'
      fullPath: '/relatorios/notas-fiscais'
      preLoaderRoute: typeof RelatoriosNotasFiscaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios/notas-fiscais-recebidas': {
      id: '/relatorios/notas-fiscais-recebidas'
      path: '/relatorios/notas-fiscais-recebidas'
      fullPath: '/relatorios/notas-fiscais-recebidas'
      preLoaderRoute: typeof RelatoriosNotasFiscaisRecebidasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios/projetos': {
      id: '/relatorios/projetos'
      path: '/relatorios/projetos'
      fullPath: '/relatorios/projetos'
      preLoaderRoute: typeof RelatoriosProjetosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios/razao-contabil': {
      id: '/relatorios/razao-contabil'
      path: '/relatorios/razao-contabil'
      fullPath: '/relatorios/razao-contabil'
      preLoaderRoute: typeof RelatoriosRazaoContabilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios/tempo': {
      id: '/relatorios/tempo'
      path: '/relatorios/tempo'
      fullPath: '/relatorios/tempo'
      preLoaderRoute: typeof RelatoriosTempoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios/vendas': {
      id: '/relatorios/vendas'
      path: '/relatorios/vendas'
      fullPath: '/relatorios/vendas'
      preLoaderRoute: typeof RelatoriosVendasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relogio/': {
      id: '/relogio/'
      path: '/relogio'
      fullPath: '/relogio/'
      preLoaderRoute: typeof RelogioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relogio/apontamento': {
      id: '/relogio/apontamento'
      path: '/relogio/apontamento'
      fullPath: '/relogio/apontamento'
      preLoaderRoute: typeof RelogioApontamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relogio/horas-por-projeto': {
      id: '/relogio/horas-por-projeto'
      path: '/relogio/horas-por-projeto'
      fullPath: '/relogio/horas-por-projeto'
      preLoaderRoute: typeof RelogioHorasPorProjetoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relogio/painel-projetos': {
      id: '/relogio/painel-projetos'
      path: '/relogio/painel-projetos'
      fullPath: '/relogio/painel-projetos'
      preLoaderRoute: typeof RelogioPainelProjetosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relogio/painel-tempo': {
      id: '/relogio/painel-tempo'
      path: '/relogio/painel-tempo'
      fullPath: '/relogio/painel-tempo'
      preLoaderRoute: typeof RelogioPainelTempoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relogio/planilha-fotos': {
      id: '/relogio/planilha-fotos'
      path: '/relogio/planilha-fotos'
      fullPath: '/relogio/planilha-fotos'
      preLoaderRoute: typeof RelogioPlanilhaFotosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relogio/projetos': {
      id: '/relogio/projetos'
      path: '/relogio/projetos'
      fullPath: '/relogio/projetos'
      preLoaderRoute: typeof RelogioProjetosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relogio/tipos-projeto': {
      id: '/relogio/tipos-projeto'
      path: '/relogio/tipos-projeto'
      fullPath: '/relogio/tipos-projeto'
      preLoaderRoute: typeof RelogioTiposProjetoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relogio/visualizacao': {
      id: '/relogio/visualizacao'
      path: '/relogio/visualizacao'
      fullPath: '/relogio/visualizacao'
      preLoaderRoute: typeof RelogioVisualizacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendas/contratos': {
      id: '/vendas/contratos'
      path: '/vendas/contratos'
      fullPath: '/vendas/contratos'
      preLoaderRoute: typeof VendasContratosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendas/faturamento': {
      id: '/vendas/faturamento'
      path: '/vendas/faturamento'
      fullPath: '/vendas/faturamento'
      preLoaderRoute: typeof VendasFaturamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendas/orcamento': {
      id: '/vendas/orcamento'
      path: '/vendas/orcamento'
      fullPath: '/vendas/orcamento'
      preLoaderRoute: typeof VendasOrcamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendas/painel-vendas': {
      id: '/vendas/painel-vendas'
      path: '/vendas/painel-vendas'
      fullPath: '/vendas/painel-vendas'
      preLoaderRoute: typeof VendasPainelVendasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendas/produtos': {
      id: '/vendas/produtos'
      path: '/vendas/produtos'
      fullPath: '/vendas/produtos'
      preLoaderRoute: typeof VendasProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendas/servicos': {
      id: '/vendas/servicos'
      path: '/vendas/servicos'
      fullPath: '/vendas/servicos'
      preLoaderRoute: typeof VendasServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendas/tabela-precos': {
      id: '/vendas/tabela-precos'
      path: '/vendas/tabela-precos'
      fullPath: '/vendas/tabela-precos'
      preLoaderRoute: typeof VendasTabelaPrecosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/google-calendar/return': {
      id: '/oauth/google-calendar/return'
      path: '/oauth/google-calendar/return'
      fullPath: '/oauth/google-calendar/return'
      preLoaderRoute: typeof OauthGoogleCalendarReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/meta/webhook': {
      id: '/api/public/meta/webhook'
      path: '/api/public/meta/webhook'
      fullPath: '/api/public/meta/webhook'
      preLoaderRoute: typeof ApiPublicMetaWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/whatsapp/webhook': {
      id: '/api/public/whatsapp/webhook'
      path: '/api/public/whatsapp/webhook'
      fullPath: '/api/public/whatsapp/webhook'
      preLoaderRoute: typeof ApiPublicWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BackupRoute: BackupRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  StyleGuideRoute: StyleGuideRoute,
  AdminEmpresasRoute: AdminEmpresasRoute,
  AdminFechamentoMensalRoute: AdminFechamentoMensalRoute,
  AdminParametrosRoute: AdminParametrosRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AgendaPessoalAgendaUnificadaRoute: AgendaPessoalAgendaUnificadaRoute,
  AgendaPessoalGoogleAgendaRoute: AgendaPessoalGoogleAgendaRoute,
  AgendaPessoalMetasRoute: AgendaPessoalMetasRoute,
  AgendaPessoalPainelRoute: AgendaPessoalPainelRoute,
  AgendaPessoalPlanejamentoRoute: AgendaPessoalPlanejamentoRoute,
  AgendaPessoalTarefasRealizadasRoute: AgendaPessoalTarefasRealizadasRoute,
  CadastrosContaCorrenteRoute: CadastrosContaCorrenteRoute,
  CadastrosFavorecidosRoute: CadastrosFavorecidosRoute,
  CadastrosGrupoFavorecidosRoute: CadastrosGrupoFavorecidosRoute,
  CadastrosGrupoProdutosRoute: CadastrosGrupoProdutosRoute,
  CadastrosImpostosRetidosRoute: CadastrosImpostosRetidosRoute,
  CadastrosMotivosPerdaRoute: CadastrosMotivosPerdaRoute,
  CadastrosOrigensRoute: CadastrosOrigensRoute,
  CadastrosProfissoesRoute: CadastrosProfissoesRoute,
  CadastrosTiposTitulosRoute: CadastrosTiposTitulosRoute,
  ContabilBalancoRoute: ContabilBalancoRoute,
  ContabilDreRoute: ContabilDreRoute,
  ContabilLancamentosRoute: ContabilLancamentosRoute,
  ContabilPlanoContasRoute: ContabilPlanoContasRoute,
  CrmAgendaRoute: CrmAgendaRoute,
  CrmFunilConfiguracaoRoute: CrmFunilConfiguracaoRoute,
  CrmLeadsRoute: CrmLeadsRoute,
  CrmPainelRoute: CrmPainelRoute,
  CrmWhatsappRoute: CrmWhatsappRoute,
  CrmWhatsappImplantacaoRoute: CrmWhatsappImplantacaoRoute,
  FinanceiroAntecipacoesRoute: FinanceiroAntecipacoesRoute,
  FinanceiroContasAPagarRoute: FinanceiroContasAPagarRoute,
  FinanceiroContasReceberRoute: FinanceiroContasReceberRoute,
  FinanceiroFluxoCaixaRoute: FinanceiroFluxoCaixaRoute,
  FinanceiroIncluirMovimentacaoRoute: FinanceiroIncluirMovimentacaoRoute,
  FinanceiroMovimentacaoRoute: FinanceiroMovimentacaoRoute,
  FinanceiroPainelFinanceiroRoute: FinanceiroPainelFinanceiroRoute,
  RelatoriosAnaliseDreRoute: RelatoriosAnaliseDreRoute,
  RelatoriosAniversariantesRoute: RelatoriosAniversariantesRoute,
  RelatoriosAntecipacoesRoute: RelatoriosAntecipacoesRoute,
  RelatoriosClassificacaoAbcRoute: RelatoriosClassificacaoAbcRoute,
  RelatoriosContasAPagarRoute: RelatoriosContasAPagarRoute,
  RelatoriosContasAReceberRoute: RelatoriosContasAReceberRoute,
  RelatoriosFavorecidoRoute: RelatoriosFavorecidoRoute,
  RelatoriosFinanceiroRoute: RelatoriosFinanceiroRoute,
  RelatoriosFotosRoute: RelatoriosFotosRoute,
  RelatoriosLogsRoute: RelatoriosLogsRoute,
  RelatoriosNotasFiscaisRoute: RelatoriosNotasFiscaisRoute,
  RelatoriosNotasFiscaisRecebidasRoute: RelatoriosNotasFiscaisRecebidasRoute,
  RelatoriosProjetosRoute: RelatoriosProjetosRoute,
  RelatoriosRazaoContabilRoute: RelatoriosRazaoContabilRoute,
  RelatoriosTempoRoute: RelatoriosTempoRoute,
  RelatoriosVendasRoute: RelatoriosVendasRoute,
  RelogioApontamentoRoute: RelogioApontamentoRoute,
  RelogioHorasPorProjetoRoute: RelogioHorasPorProjetoRoute,
  RelogioPainelProjetosRoute: RelogioPainelProjetosRoute,
  RelogioPainelTempoRoute: RelogioPainelTempoRoute,
  RelogioPlanilhaFotosRoute: RelogioPlanilhaFotosRoute,
  RelogioProjetosRoute: RelogioProjetosRoute,
  RelogioTiposProjetoRoute: RelogioTiposProjetoRoute,
  RelogioVisualizacaoRoute: RelogioVisualizacaoRoute,
  VendasContratosRoute: VendasContratosRoute,
  VendasFaturamentoRoute: VendasFaturamentoRoute,
  VendasOrcamentoRoute: VendasOrcamentoRoute,
  VendasPainelVendasRoute: VendasPainelVendasRoute,
  VendasProdutosRoute: VendasProdutosRoute,
  VendasServicosRoute: VendasServicosRoute,
  VendasTabelaPrecosRoute: VendasTabelaPrecosRoute,
  RelatoriosIndexRoute: RelatoriosIndexRoute,
  RelogioIndexRoute: RelogioIndexRoute,
  OauthGoogleCalendarReturnRoute: OauthGoogleCalendarReturnRoute,
  ApiPublicMetaWebhookRoute: ApiPublicMetaWebhookRoute,
  ApiPublicWhatsappWebhookRoute: ApiPublicWhatsappWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
