// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vbbfmmjohdmocnaxgmmd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZiYmZtbWpvaGRtb2NuYXhnbW1kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzNTMwMjUsImV4cCI6MjA2MDkyOTAyNX0.02t6j9Bzx-DyoutYFD7MlVedEr_RWoQOF6Gat_7gw14";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);